"""Initial Migration

Revision ID: 652692cf87d0
Revises: 
Create Date: 2020-11-05 17:23:39.694107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652692cf87d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.drop_index('ix_users_room_no', table_name='users')
    op.drop_column('users', 'room_no')
    op.drop_column('users', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('room_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_users_room_no', 'users', ['room_no'], unique=True)
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
