"""additional columns migration

Revision ID: d1306fd4cb08
Revises: 58ffc8de2097
Create Date: 2020-11-05 14:15:36.129893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1306fd4cb08'
down_revision = '58ffc8de2097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.drop_index('ix_users_room_no', table_name='users')
    op.drop_column('users', 'room_no')
    op.drop_column('users', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('room_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_users_room_no', 'users', ['room_no'], unique=True)
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
